version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:latest
  resque:
    build: .
    command: bundle exec rake resque:work QUEUE='*'
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - resque
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@db:5432/myapp_development}
  resque-scheduler:
    build: .
    command: bundle exec rake resque:scheduler
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - redis
